### ISSUE TITLE
Wrong typo in command line --with-token flag

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#104]
On this page:

https://reliably.com/docs/reference/cli/reliably-auth-login/

```
Alternatively, pass in a token on standard input by using %[1]s--with-token%[1]s.
```

I think this one has to be fixed in the cli code.

cc @dmartin35

**Comment by dmartin35** [comment]
I manually changed on the doc, so that the fix is available right now.
I also fixed the long desc of the auth login command on the CLI repo, so that it will be properly generated on next release ;
see releated issue https://github.com/reliablyhq/cli/issues/50

**Comment by Lawouach** [comment]
I think that fix won't be the right one. That page is autogenerated by the cli.

**Comment by Lawouach** [comment]
Oops. I misread you did fix it there too
