### ISSUE TITLE
Missing prefix $ character in command line examples

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#105]
In all samples of this section:

https://reliably.com/docs/getting-started/install/#installing-reliably-on-linux-ubuntu

**Comment by mperrien** [comment]
@reliablyhq/documentation I'll fix it. I'm always wondering if it's a good practice, as it makes copying and pasting less easy.

**Comment by mperrien** [comment]
There's a PR ready to be merged if we want to proceed.

For example the curl manual doesn't put those:
https://curl.se/docs/manual.html

**Comment by mperrien** [comment]
As @dmartin35 was surprised too that there wasn't a $ prefix, I'll merge the PR.
