### ISSUE TITLE
Left-hand menu styles

### ISSUE THREAD

**Issue by mperrien** [reliablyhq/documentation#109]
Update styles for the left-hand menu.
- colors
- bullet points
- vertical border
- header

cf https://3.basecamp.com/3495499/buckets/18392607/messages/3452666699#__recording_3460680813

**Comment by Lawouach** [comment]
I could see the benefit of having a different colour for the active page. Like this:


![image](https://user-images.githubusercontent.com/769982/107527091-c9e03280-6bb8-11eb-91b7-4b73cf46c57c.png)

**Comment by Lawouach** [comment]
As well as a left vertifcal line too. This helps understanding where you are.
