### ISSUE TITLE
Make inline code blocks stand out more.

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#123]
I think the code doesn't stand out very much on this for instance:

![image](https://user-images.githubusercontent.com/769982/107645423-efcd0c00-6c78-11eb-8267-6a8a3976663b.png)

**Comment by Lawouach** [comment]
Maybe a background colour, as was suggested by Beto?

**Comment by mperrien** [comment]
Beto suggested #e1edeb

(Do not use this color directly: create --blue-200 variable. And rename --blue-light to --blue-100).

**Comment by Lawouach** [comment]
I'm guessing this only works for `<pre />` right. because I see some places where it's not highlighted still:

![image](https://user-images.githubusercontent.com/769982/107787446-63414d00-6d4f-11eb-8bb3-51d30fc050d1.png)

**Comment by mperrien** [comment]
It works for `p > code`

It means `code` elements which are direct descendants of paragraphs. It prevents weird behaviors in markdown notes (admonitions) where the colors might not match, and in <pre>, which are actual code blocks (the ones with a dark background and syntax highlighting).

Your example works all right for me, locally and in staging.

It is not deployed to production yet, as I'm closing a few other issues.

**Comment by mperrien** [comment]
Another problem is that code blocks in the Cobra-generated markdown doesn't get styled by Prism (the syntax highlighter), but I'll open a different issue.

**Comment by Lawouach** [comment]
Oh yea, I had to hard refrech to see it in staging. Let's close this one in favour of #134.
