### ISSUE TITLE
Download URLs aren't consistant in the Install page

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#124]
```
https://github.com/reliablyhq/cli/releases/latest/download/reliably-darwin-amd64
https://github.com/reliablyhq/cli/releases/download/v0.3.0/reliably-linux-amd64
```

which is it?

**Comment by dmartin35** [comment]
In the docs, we shall always use the URL with latest, as GH is redirecting itself to the specific tag version (that is the latest one)

Using latest URLs ensure we won't have change URLs every time we make a new release

So we shall not target a specific tag version in the download links
