### ISSUE TITLE
Update the urls and version as we release new versions

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#125]
On the install page, we should automate the urls and versions automatically (through a GH flow probably)

**Comment by dmartin35** [comment]
I don't think this one is relevant any more, if we use "latest" in the download Urls, we won't have to bother changing them . Github is redirecting itself to the correct tag

**Comment by dmartin35** [comment]
see related issue #124  The PR will make all links downloadable using a latest URL (that is dynamically redirected to the latest tag by Github)

**Comment by Lawouach** [comment]
true for URL but we still have the problem of the version:

![image](https://user-images.githubusercontent.com/769982/107783786-ec09ba00-6d4a-11eb-927b-1c08ebf3cbfd.png)

**Comment by dmartin35** [comment]
maybe we can just keep the sentence with the command usage

```
You can check everything is working with the `reliably --version` and you're
ready to [login](../login/).
```

and removes the following block
```
 ` ` ` console 
 $ reliably --version
 Reliably CLI v0.2.0
 ` ` `
```

**Comment by Lawouach** [comment]
That is sensible and less complicated.
