### ISSUE TITLE
remove the overview menu entry 

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#126]
For instance:

![image](https://user-images.githubusercontent.com/769982/107661120-40e4fc00-6c89-11eb-92e3-5e7b754859cc.png)

I should have the page changing to the Overview's content when I clicked Getting Started.

The Overview menu item creates noise and is confusing.

**Comment by mperrien** [comment]
Clicking on "Getting started" is a button that opens the submenu, not a link.

If we make it a link, we will lose the possibility to open the submenu from the home page and display all the possible first-level options without changing the page. Is this what we want?

We could make "Getting Started" a link and the chevron (>) a button to open the submenu, but I've always found this hard to discover, while also being a very small button.

**Comment by Lawouach** [comment]
I agree on the link vs button issue.

But we are three now to find the Overview page to be hard to discover because it requires an additional click. It's also noise on the menu item. So I'd say we still need a solution there.

**Comment by mperrien** [comment]
I've looked at a few other pieces of documentation to see how they were doing (not counting Gatsby, who does exactly that, obviously).

- **[Stripe](https://stripe.com/docs)** does the same thing as we do, except they don't have a left-hand menu when you're on the /docs/ URL. you navigate to sections using only the header menu. It could work.
- **[Algolia](https://www.algolia.com/doc/)** has no overview page. When opening a section from the left-hand menu, you get links to the content for this section. for example /getting-started/what-is-algolia/. It means /getting-started/ is a 404 page. I don't like URLs to break this way, it's not recommended.
- I had the feeling **mkdocs** did the same: it does. Eg [Chaos Toolkit docs](https://docs.chaostoolkit.org)
- **[React](https://reactjs.org/docs/getting-started.html)** as no hierarchy in its documentation. The hierarchy in their right-hand navigation is not reflected in the URLs:  all pages are direct children of /docs. It means clicking on a section title will open this section, revealing other links on which you can click on. It also means their is no "home" (or overview) for the "Advanced Guides" section, for example.
- In **[Rust](https://doc.rust-lang.org/book/title-page.html)**, the section headings are, but it means the sections can't collapse, making it hard to scan for content.

Any other suggestion is welcome.

**Comment by Lawouach** [comment]
Excellent research @mperrien 

I wonder what you mean with Stripe. They don't seem to have a jumping menu like Gatsby or us. They just open up the tree. 

Oh no, as you said, the top level menu is at header section. It's actually good. Interestingly, I felt exactly that way when I use the the three items at the top right of our menu to navigate.

Why am I surprised that Stripe has nailed it again? :)

**Comment by mperrien** [comment]
In fact, we have what they have, plus the sidebar on the home page.

I think that sidebar is useful, as it offers a glimpse of the whole content before you make a choice. But if it's more a distraction, it can be hidden.

Another difference is that their menu is (fully) left-aligned, while ours is less visible on the right. Their choice is not as aesthetically pleasing, but it seems to work. I don't "see" our menu now that it is on the right, but admittedly I wasn't using it a lot when it was on the left. (It wasn't exactly positioned like theirs is, neither.)

**Comment by mperrien** [comment]
The menu has been rediesigned. Closing.
