### ISSUE TITLE
Is it possible to have a different page title metadata from the visible page header title?

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#128]
So for instance, for https://reliably.com/docs/guides/kubectl-plugin/

Leave "Run Reliably as a kubectl Plugin" visible to the user but turn it to "How to run Reliably as a kubectl Plugin | Reliably.com" in the html metadata.

This would help SEO.

**Comment by mperrien** [comment]
Yes, it is.
The <title> meta comes from the Markdown front matter, while the content title is part of the Markdown.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/348229/107752016-738d0400-6d1e-11eb-90be-470e31fb522d.png">

**Comment by Lawouach** [comment]
Awesome. Probably worth we document somewhere the right way to fill these.
