### ISSUE TITLE
Update screenshots with discover output

### ISSUE THREAD

**Issue by dmartin35** [reliablyhq/documentation#138]
CLI discover output shows the level of suggestions, hence the output is modified
(cc https://github.com/reliablyhq/documentation/pull/137)

There are few screen shots that would need to be re-done:
- docs/guides/ci-pipeline/github-action/images/reliably-gh-action-suggestions.png
- docs/guides/ci-pipeline/circle-ci/images/circle-ci-pipeline-failed.png
- docs/guides/ci-pipeline/gitlab-pipeline/images/output-screen.png
- docs/guides/ci-pipeline/jenkins/images/jenkins-console-output.png

**Comment by Lawouach** [comment]
This should also be updated with the new format (tabbed, etc.) to make them more impactful.

**Comment by Lawouach** [comment]
cc @gtfisher
