### ISSUE TITLE
Found the numbers next to the sections confusing

### ISSUE THREAD

**Issue by russmiles** [reliablyhq/documentation#146]
The numbers next to the sections of the documentation seem to indicate the number of sub-sections? However I found this confusing as there is usually an "Overview" section listed as well, so initially I found myself asking what the number was even for. Seemed to tell me something I didn't care to know too much, and then confused me with it as well!

<img width="275" alt="Screenshot 2021-02-22 at 09 50 49" src="https://user-images.githubusercontent.com/104529/108691700-ae97f000-74f3-11eb-870e-e735af17f7ce.png">

**Comment by Lawouach** [comment]
Related to https://github.com/reliablyhq/documentation/issues/126

**Comment by mperrien** [comment]
The menu has been modified, this doesn't exist anymore.
