### ISSUE TITLE
Change name of sestion for live cluster

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#153]
No need to specify "live" in the live cluster facility. It's well understood if you talk about a cluster, it's a running one.

![image](https://user-images.githubusercontent.com/769982/109165046-65f26800-777b-11eb-9827-5ba13a38720b.png)

**Comment by mperrien** [comment]
I'm also wondering if "with" is the right word here. Would "on a cluster" or "against a cluster" fit better?
