### ISSUE TITLE
kubectl is not required as the docsays

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#154]
The doc states:

![image](https://user-images.githubusercontent.com/769982/109165151-85899080-777b-11eb-9c74-4011cff9a5fe.png)

You don't have to have kubectl but you must have a valud kube confi file. Usually this is provisionned by the kubectl config indeed but not mandatory (you can get a config file from elsewhere). This will remove a dependency need.

**Comment by gtfisher** [comment]
closed by #158
