### ISSUE TITLE
Link not working in docs

### ISSUE THREAD

**Issue by russmiles** [reliablyhq/documentation#175]
The link indicated below goes to a 404 in the docs.![image](https://user-images.githubusercontent.com/104529/113735173-e8176a00-96f3-11eb-8bf9-1b4309b3cad2.jpeg)

**Comment by russmiles** [comment]
Also the link in the references paragraph heads to a 404 too.

"Read the Reliably CLI SLO Init command reference for a complete list of options."

**Comment by mperrien** [comment]
Thanks, Russ, Xavier has noticed them too.
Gridsome not using the /docs/ path prefix for markdown links. Might have to use relative links when linking from a page to another.
Manually adding the /docs/ before each link would make the work in staging and production, but not locally...
