### ISSUE TITLE
Deploy CLI reference to production when a new version is released

### ISSUE THREAD

**Issue by mperrien** [reliablyhq/documentation#198]
The current GitHub Action builds the documentation and pushes the changes to staging when a new version of the CLI is released.

It could, and should, also deploy to production.

**Comment by dmartin35** [comment]
First solution is to trigger the workflow to create a tag (that will trigger the deploy to prod), when a new commit is made on `main` branch for a change in the `cobra-md` folder. As it's supposed only to be the CLI workflow to update that folder.

If we want the CLI only to trigger that doc release to prod, we would need to make a tag from the CLI right after pushing the commit . But that implies the CLI workflow is aware of how to release the doc to prod, which I don"t quite like if we can avoid (reason for the first choice)

We know have the doc repo itself being autonomous on when to release itself to prod:
- on manual trigger 
- on a commit to cobra-md on main branch only
