### ISSUE TITLE
Should we have a migration page in the How it works section?

### ISSUE THREAD

**Issue by Lawouach** [reliablyhq/documentation#288]
As we changedt he format of the manifest, I wondered if we should have a page specific for helping users migrate between versions (the manifest but could also be the API in the future...)

I could see a first page with a section that explains how to migrate the manifest manually at least.

**Comment by xaah** [comment]
I can look into writing this if no one's taken it?

**Comment by Lawouach** [comment]
Great, I would have otherwise but feel free :)

**Comment by xaah** [comment]
@Lawouach yeah sorry I just noticed it was self assigned recently, apologies. Sounds good I'll work on it.

**Comment by xaah** [comment]
I've added a migration guide and edited a few pages that had the old manifest in them. https://github.com/reliablyhq/documentation/pull/290/files

**Comment by mperrien** [comment]
Can this issue be closed since #290 has been merged by @xaah, @Lawouach?

**Comment by Lawouach** [comment]
Yes  : )
