### ISSUE TITLE
Add Getting Started page for Orgnization management

### ISSUE THREAD

**Issue by mperrien** [reliablyhq/documentation#296]

**Comment by russmiles** [comment]
I'm happy to draft a first version of this, this week, if no one else is working on it?

**Comment by russmiles** [comment]
@dmartin35 you're assigned, is this work in progress?

**Comment by xaah** [comment]
@russmiles there is this page: https://reliably.com/docs/guides/how-it-works/org-management/

It was moved from Getting Started to Guides after our chat about docs a couple weeks ago.

**Comment by russmiles** [comment]
Ah, that looks like what I was looking for. In which case, shall we close this issue @xaah ?

**Comment by xaah** [comment]
@russmiles yeah sounds good, closing now.
