### ISSUE TITLE
Should we be more specific when explaining how we compute SLO reports data?

### ISSUE THREAD

**Issue by mperrien** [reliablyhq/documentation#311]
In this page: https://reliably.com/docs/guides/how-it-works/slo-reports/

**Comment by mperrien** [comment]
In this page: https://reliably.com/docs/guides/how-it-works/slo-reports/

**Comment by xaah** [comment]
Report produces a table from pre-computed data. The agent is computing the indicators, and the server is calculating the delta between target/indicator. I just mention to clarify that maybe the report section is not the best place for that. In the past the report command performed calculations but not anymore.
