### ISSUE TITLE
Copy Update: Docs Home

### ISSUE THREAD

**Issue by djgbradley** [reliablyhq/documentation#53]
/** New copy to bolster brand voice, and keep the messaging super consistent **/

Welcome to Reliably!

We're here to lend a helping hand. Reliably will automatically surface and respond to reliability issues while you code, build, and run your applications. It's that simple.

/** illustration goes here, as before **/

Reliably works wherever you do – connecting seamlessly to GitHub and GitLab Continuous Integration and Delivery (CI/CD) workflows and pipelines. We also offer a handy CLI for local use.

Choose your preferred weapon below to get started for free.

[GitHub](https://docs.reliably.com/start/github/)  |  [GitLab](https://docs.reliably.com/start/gitlab/)  |  [CLI](https://docs.reliably.com/tools/cli/)

Want to know more? [Check out how Reliably works under the hood...](https://docs.reliably.com/howitworks/)

**Comment by russmiles** [comment]
Should that be a colon after "get started for free:" @djgbradley ?

**Comment by djgbradley** [comment]
> Should that be a colon after "get started for free:" @djgbradley ?

Yes, a colon is a good idea here.
