### ISSUE TITLE
Better explain how to install the CLI

### ISSUE THREAD

**Issue by mperrien** [reliablyhq/documentation#65]
This page only explains how to download it: https://docs.reliably.com/tools/cli/

I think I know how to install it on my Mac. I guess it's the same on Linux. I'm not sure it's the same on Windows. Anyway, I shouldn't have to look elsewhere on the internet if I'm wrong or don't know.

Also, explain how to use the md5 file. I know what it's for, I don't know how to use it. I could Google it, but I clearly won't. If we make the file available, let's make its usage clear for everyone. Maybe just with a link to a dedicated page. Maybe even a page we don't own.

Let's create the lowest barrier possible.

**Comment by gtfisher** [comment]
For Windows, you need to download the windows image and add a .exe extension it will then execute from a command prompt (not tried it in PowerShell yet)

**Comment by russmiles** [comment]
This sounds like a useful quick win. Do you have the time to fix this up gents @mperrien @gtfisher ?
